/*
 * Part of the EMFexplorer project.
 * Copyright (c) 2004-2026 Smith Charles.
 * Released under the MIT License (see LICENSE file at root).
 */
#define IDR_SRVR_INPLACE                4
#define IDR_SRVR_EMBEDDED               5
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDR_MAINFRAME                   128
#define IDR_EMFEXPTYPE                  129
#define IDD_SCEMFINSPECT_DIALOG         130
#define IDR_TB_GDIPLUS                  131
#define IDD_OPT_GENPANE                 137
#define IDD_OPT_COLORPANE               139
#define IDD_PROPPAGE_SETTINGS           142
#define IDD_DOC_REFLOW                  143
#define IDD_PROPPAGE_GENERAL            200
#define IDR_CTX_MENU                    201
#define IDD_PROPPAGE_GDIPLUS            202
#define IDC_COMBO_GDIP_TEXTHINTING      202
#define IDC_COMBO_GDIP_TEXTCONTRAST     203
#define IDD_PROPPAGE_COLORS             204
#define IDC_EDIT_MARGINS_L              204
#define IDC_EDIT_MARGINS_T              205
#define IDC_COMBO_GDIP_SMOOTHING        207
#define IDC_COMBO_GDIP_INTERPOLATION    208
#define IDC_COMBO_GDIP_PIXELOFFSET      210
#define IDC_RADIO_RVIDEO_NONE           214
#define IDC_COMBO_CTLCOLOR_RGB          217
#define IDC_CHECK_PICTURE_BORDER        218
#define IDC_CHECK_PICTURE_SHADOW        219
#define IDC_RADIO_PAPERCOLOR_TRANS      220
#define IDC_RADIO_CTLCOLOR_TRANS        221
#define IDC_RADIO_CTLCOLOR_SYS          222
#define IDC_RADIO_CTLCOLOR_RGB          223
#define IDC_RADIO_ORIENT0               224
#define IDC_RADIO_ORIENT90              225
#define IDC_RADIO_ORIENT180             226
#define IDC_RADIO_ORIENT270             227
#define IDC_RADIO_PAPERCOLOR_SYS        228
#define IDC_RADIO_PAPERCOLOR_RGB        229
#define IDC_COMBO_PAPERCOLOR_SYS        230
#define IDC_COMBO_CTLCOLOR_SYS          231
#define IDC_COMBO_CTL_BORDER            232
#define IDC_BTN_STOPBRK                 1001
#define IDC_PROGRESS_BRK                1002
#define IDC_EDIT_BRKCOUNT               1003
#define IDC_RADIO_TRANSP_NORMAL         1005
#define IDC_RADIO_TRANSP_FULL           1006
#define IDC_RADIO_TRANSP_SKIPBITMAPS    1007
#define IDC_RADIO_RVIDEO_FULL           1008
#define IDC_RADIO_RVIDEO_SKIPBITMAPS    1009
#define IDC_COMBO_OPTGEN_ZOOM           1010
#define IDC_COMBO_PAPERCOLOR_RGB        1011
#define IDC_RADIO_OPTGEN_USEDFLT        1012
#define IDC_RADIO_OPTGEN_USEDOC         1013
#define IDC_CHK_OPTGEN_USEGDIP          1019
#define IDC_RADIO_OPTGEN_USELAST        1020
#define IDC_RADIO_OPTGEN_SAVECONVERTED  1021
#define IDC_RADIO_OPTGEN_SAVEWYSIWYG    1022
#define IDC_EDIT_MARGINS_R              1024
#define IDC_EDIT_MARGINS_B              1025
#define IDC_LST_PAGES                   1026
#define IDC_BTN_TOP                     1027
#define IDC_BTN_LEFT                    1028
#define IDC_BTN_UP                      1029
#define IDC_BTN_RIGHT                   1030
#define IDC_BTN_BOTTOM                  1031
#define IDC_BTN_DOWN                    1032
#define IDC_EDIT_CREDIT                 1034
#define IDC_EDIT_URL                    1035
#define IDC_EDIT_COMMENT                1036
#define IDC_EDIT_PAGE_POS               1037
#define IDC_BTN_REPLACE                 1038
#define IDC_PICT_CURPAGE                1039
#define IDC_PICT_ALLPAGES               1040
#define IDC_EDIT_CURFILE                1041
#define IDC_EDIT_DPI                    1044
#define IDC_EDIT_SIZE                   1046
#define IDC_BTN_SAVERTF                 1047
#define IDC_BTN_COPYALL                 1048
#define IDC_BTN_REMOVE                  1049
#define IDC_BTN_ADD                     1050
#define IDC_EDIT_DOC_DIR                1051
#define IDC_CHK_DEFAULT                 1052
#define IDC_BTN_VALIDATE                1053
#define ID_CANCEL_EDIT_SRVR             32769
#define ID_TBNAV_FIRST                  32772
#define ID_TBNAV_PREV                   32773
#define ID_TBNAV_NEXT                   32774
#define ID_TBNAV_LAST                   32775
#define ID_TB_DPI_DEC                   32778
#define ID_TB_DPI_INC                   32779
#define ID_TB_DPI_100                   32781
#define ID_TB_DPI_MONITOR               32785
#define ID_TB_PAGE_ROTATELEFT           32787
#define ID_TB_PAGE_ROTATERIGHT          32788
#define ID_TBDOC_BKCOLOR                32789
#define ID_TB_PAGE_REVERSEVIDEO         32790
#define ID_TBNAV_TOPAGE                 32791
#define ID_TBVIEW_ZOOM                  32792
#define ID_TBVIEW_BKCOLOR               32793
#define ID_VIEW_EMF_ASTEXT              32794
#define ID_TBDOC_USEGDIP                32795
#define ID_TBGDIP_TEXTRENDERING         32796
#define ID_TBGDIP_TEXTCONTRAST          32797
#define ID_TBGDIP_CURVESMOOTHING        32798
#define ID_TBGDIP_IMAGESMOOTHING        32799
#define ID_TBGDIP_IMAGEPIXELSOFFSET     32800
#define ID_VIEW_GDIP_BAR                32801
#define ID_TOOLS_OPTIONS                32802
#define ID_FILE_SAVEALL                 32803
#define ID_TBDOC_RESIZEALL              32804
#define ID_TBDOC_SETTINGS               32805
#define ID_TBDOC_REFLOW                 32806
#define ID_FILE_SAVEPAGE                32807
#define ID_TOOLS_PAGE_URL               32808
#define ID_TBDOC_ADD_PAGES              32809
#define ID_TBDOC_REMOVE_PAGE            32810
#define ID_INDICATOR_PAGE               59142
#define IDS_PPG_GENERAL                 61446
#define IDS_PPG_GDIP                    61447
#define IDS_PPG_COLORS                  61448
#define IDS_PPG_DFLT_SETTINGS           61449
#define IDS_PPG_DOC_SETTINGS            61450
#define IDS_EMFXMERGE_ERR               61451
#define IDS_REFLOWADDFILES_ERR          61452
#define IDS_REFLOW_CONFIRM_RENAME       61453
#define IDS_FILE_UNKNOWN                61454
#define IDS_FILEMIX_ERR                 61455
#define IDS_FILE_REPLACE_ERR            61456
#define IDS_FILE_INSERTONE_FAILED       61457
#define IDS_FILE_INSERTMANY_FAILED      61458
#define IDS_FILE_INSERTTYPE_ERR         61459
#define IDS_FILE_CONFIRM_COPY           61460
#define IDS_FILE_LOADTYPE_ERR           61461
#define IDS_FILE_LOAD_ERR               61462
#define IDS_DLG_TITLE_OPTIONS           61463
#define IDS_DLG_TITLE_DOCSETTINGS       61464
#define IDS_DLG_TITLE_UNSAVEDDOCSETTINGS 61465
#define IDS_FILE_RENAME_ERR             61466
#define IDS_FILE_RENAME_ERRLAST         61467

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        144
#define _APS_NEXT_COMMAND_VALUE         32811
#define _APS_NEXT_CONTROL_VALUE         1054
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
